"use strict";
const STORAGE_KEY="premiumDigitalCardProfile";
const THEME_KEY="digitalCardTheme";
const VISIBILITY_LABELS={description:"Description",saveContact:"Save Contact button",quickActions:"Quick action buttons",phone:"Phone 1",phone2:"Phone 2",whatsapp:"WhatsApp",email:"Email",website:"Website",location:"Location",facebook:"Facebook",instagram:"Instagram",linkedin:"LinkedIn",twitter:"X / Twitter",tiktok:"TikTok",youtube:"YouTube",businessLinks:"Business Links",catalog:"Catalog",customBusiness:"Extra business link",services:"Services",gallery:"Gallery",video:"Video",qr:"QR code",finalCTA:"Final contact button",logo:"Business logo"};
const defaults={fullName:"John Smith",position:"Owner / Founder",company:"Premium Business LLC",city:"Chicago",state:"Illinois",description:"Professional services with quality, reliability and attention to detail.",phone:"(708) 555-1234",phoneRaw:"+17085551234",phone2:"",phone2Raw:"",whatsapp:"",whatsappRaw:"",email:"hello@example.com",website:"https://example.com",facebook:"",instagram:"",linkedin:"",twitter:"",tiktok:"",youtube:"",catalog:"",catalogFile:"",catalogFileName:"",customBusinessLabel:"More Information",customBusinessSubtitle:"Open business link",customBusinessUrl:"",profileImage:"",coverImage:"",logoImage:"",galleryImages:[],videoUrl:"",service1Title:"Service One",service1Description:"Add a short description of your service here.",service1Icon:"fa-house",service2Title:"Service Two",service2Description:"Add another service description here.",service2Icon:"fa-screwdriver-wrench",service3Title:"Service Three",service3Description:"Customize this section for any type of business.",service3Icon:"fa-paint-roller",finalCtaTitle:"Let's Connect",finalCtaText:"Have a question or want to work together? Contact us today.",finalCtaLabel:"Contact Now",theme:"gold",visibility:Object.fromEntries(Object.keys(VISIBILITY_LABELS).map(k=>[k,true]))};
function getSavedProfile(){try{const raw=localStorage.getItem(STORAGE_KEY);if(!raw)return structuredCloneSafe(defaults);const p=JSON.parse(raw);return {...structuredCloneSafe(defaults),...p,visibility:{...defaults.visibility,...(p.visibility||{})},galleryImages:Array.isArray(p.galleryImages)?p.galleryImages:[]};}catch(e){console.error(e);return structuredCloneSafe(defaults)}}
function structuredCloneSafe(v){return JSON.parse(JSON.stringify(v))}
function setVal(id,v){const e=document.getElementById(id);if(e)e.value=v||""}
function getVal(id){const e=document.getElementById(id);return e?e.value.trim():""}
function normalizeURL(v){if(!v)return"";if(/^https?:\/\//i.test(v))return v;return"https://"+v}
function normalizePhone(v){return v?"+"+v.replace(/\D/g,""):""}
function setStatus(msg,type="success"){const e=document.getElementById("saveStatus");if(!e)return;e.textContent=msg;e.className="save-status "+type;clearTimeout(window._statusTimer);window._statusTimer=setTimeout(()=>{e.textContent="";e.className="save-status"},3500)}
function buildVisibility(){const grid=document.getElementById("visibilityGrid");grid.innerHTML="";Object.entries(VISIBILITY_LABELS).forEach(([key,label])=>{const l=document.createElement("label");l.className="toggle-card";l.innerHTML=`<input type="checkbox" id="vis_${key}"><span>${label}</span>`;grid.appendChild(l)})}
function loadVisibility(v){Object.keys(VISIBILITY_LABELS).forEach(k=>{const e=document.getElementById("vis_"+k);if(e)e.checked=v?.[k]!==false})}
function readVisibility(){return Object.fromEntries(Object.keys(VISIBILITY_LABELS).map(k=>[k,document.getElementById("vis_"+k)?.checked!==false]))}
function updatePreview(imgId,placeholderId,data){const img=document.getElementById(imgId),ph=document.getElementById(placeholderId);if(!img)return;if(data){img.src=data;img.style.display="block";if(ph)ph.style.display="none"}else{img.removeAttribute("src");img.style.display="none";if(ph)ph.style.display="flex"}}
function loadForm(){const p=getSavedProfile();["fullName","position","company","city","state","description","phone","phone2","whatsapp","email","website","facebook","instagram","linkedin","twitter","tiktok","youtube","catalog","customBusinessLabel","customBusinessSubtitle","customBusinessUrl","videoUrl","service1Title","service1Description","service1Icon","service2Title","service2Description","service2Icon","service3Title","service3Description","service3Icon","finalCtaTitle","finalCtaText","finalCtaLabel"].forEach(id=>setVal(id,p[id]));updatePreview("logoPreview","logoPlaceholder",p.logoImage);updatePreview("profilePreview","profilePlaceholder",p.profileImage);updatePreview("coverPreview","coverPlaceholder",p.coverImage);renderGalleryPreview(p.galleryImages);loadVisibility(p.visibility);setThemeActive(p.theme)}
function setThemeActive(theme){document.querySelectorAll(".admin-theme").forEach(b=>b.classList.toggle("active",b.dataset.theme===theme))}
function compressImage(file,maxW,maxH,q=.78){return new Promise((resolve,reject)=>{if(!file.type.startsWith("image/"))return reject(new Error("Not an image"));const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{let w=im.width,h=im.height,ratio=Math.min(1,maxW/w,maxH/h);w=Math.round(w*ratio);h=Math.round(h*ratio);const c=document.createElement("canvas");c.width=w;c.height=h;c.getContext("2d").drawImage(im,0,0,w,h);resolve(c.toDataURL("image/jpeg",q))};im.onerror=reject;im.src=r.result};r.onerror=reject;r.readAsDataURL(file)})}
async function imageUpload(inputId,field,imgId,phId,maxW,maxH,q){const input=document.getElementById(inputId);input.addEventListener("change",async e=>{const f=e.target.files?.[0];if(!f)return;try{const data=await compressImage(f,maxW,maxH,q);const p=getSavedProfile();p[field]=data;localStorage.setItem(STORAGE_KEY,JSON.stringify(p));updatePreview(imgId,phId,data);setStatus("Image updated.")}catch(err){setStatus("Could not process that image.","error")}})}
function renderGalleryPreview(images){const box=document.getElementById("galleryPreview");if(!box)return;box.innerHTML="";(images||[]).forEach(src=>{const img=document.createElement("img");img.src=src;box.appendChild(img)})}
async function handleGallery(files){const chosen=[...files].slice(0,6);if(!chosen.length)return;try{const images=[];for(const f of chosen)images.push(await compressImage(f,1200,900,.68));const p=getSavedProfile();p.galleryImages=images;localStorage.setItem(STORAGE_KEY,JSON.stringify(p));renderGalleryPreview(images);setStatus("Gallery updated.")}catch(e){setStatus("Could not process gallery images.","error")}}
function handleCatalog(file){if(!file)return;if(file.type!=="application/pdf")return setStatus("Please choose a PDF.","error");if(file.size>1024*1024)return setStatus("That PDF is over 1 MB. Use Catalog URL instead.","error");const r=new FileReader();r.onload=()=>{const p=getSavedProfile();p.catalogFile=r.result;p.catalogFileName=file.name;localStorage.setItem(STORAGE_KEY,JSON.stringify(p));setStatus("Small PDF stored.")};r.readAsDataURL(file)}
function saveProfile(){const old=getSavedProfile();const p={...old};["fullName","position","company","city","state","description","phone","phone2","whatsapp","email","facebook","instagram","linkedin","twitter","tiktok","youtube","customBusinessLabel","customBusinessSubtitle","videoUrl","service1Title","service1Description","service1Icon","service2Title","service2Description","service2Icon","service3Title","service3Description","service3Icon","finalCtaTitle","finalCtaText","finalCtaLabel"].forEach(id=>p[id]=getVal(id));p.website=normalizeURL(getVal("website"));p.catalog=normalizeURL(getVal("catalog"));p.customBusinessUrl=normalizeURL(getVal("customBusinessUrl"));p.facebook=normalizeURL(p.facebook);p.instagram=normalizeURL(p.instagram);p.linkedin=normalizeURL(p.linkedin);p.twitter=normalizeURL(p.twitter);p.tiktok=normalizeURL(p.tiktok);p.youtube=normalizeURL(p.youtube);p.phoneRaw=normalizePhone(p.phone);p.phone2Raw=normalizePhone(p.phone2);p.whatsappRaw=normalizePhone(p.whatsapp);p.visibility=readVisibility();p.theme=document.querySelector(".admin-theme.active")?.dataset.theme||old.theme||"gold";if(!p.fullName)return setStatus("Please enter a name.","error");try{localStorage.setItem(STORAGE_KEY,JSON.stringify(p));localStorage.setItem(THEME_KEY,p.theme);setStatus("Changes saved successfully.")}catch(e){setStatus("Browser storage is full. Remove some images or use hosted image URLs.","error")}}
function resetAll(){if(!confirm("Reset the complete card to defaults?"))return;localStorage.removeItem(STORAGE_KEY);localStorage.removeItem(THEME_KEY);loadForm();setStatus("Card reset.")}
document.addEventListener("DOMContentLoaded",()=>{buildVisibility();loadForm();imageUpload("logoUpload","logoImage","logoPreview","logoPlaceholder",900,600,.8);imageUpload("profileUpload","profileImage","profilePreview","profilePlaceholder",700,700,.8);imageUpload("coverUpload","coverImage","coverPreview","coverPlaceholder",1600,900,.76);document.getElementById("galleryUpload").addEventListener("change",e=>handleGallery(e.target.files));document.getElementById("clearGallery").addEventListener("click",()=>{const p=getSavedProfile();p.galleryImages=[];localStorage.setItem(STORAGE_KEY,JSON.stringify(p));renderGalleryPreview([]);setStatus("Gallery cleared.")});document.getElementById("catalogUpload").addEventListener("change",e=>handleCatalog(e.target.files?.[0]));document.querySelectorAll("[data-clear-image]").forEach(b=>b.addEventListener("click",()=>{const field=b.dataset.clearImage,p=getSavedProfile();p[field]="";localStorage.setItem(STORAGE_KEY,JSON.stringify(p));const m={logoImage:["logoPreview","logoPlaceholder"],profileImage:["profilePreview","profilePlaceholder"],coverImage:["coverPreview","coverPlaceholder"]}[field];if(m)updatePreview(...m,"");setStatus("Image removed.")}));document.querySelectorAll(".admin-theme").forEach(b=>b.addEventListener("click",()=>{setThemeActive(b.dataset.theme)}));document.getElementById("saveProfile").addEventListener("click",saveProfile);document.getElementById("resetProfile").addEventListener("click",resetAll)})
