import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getFirestore, doc, getDoc } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyDf12K0m93K4cWSotDcSg2fIS-s3uaLW_Y",authDomain:"jmx-digital-card.firebaseapp.com",projectId:"jmx-digital-card",storageBucket:"jmx-digital-card.firebasestorage.app",messagingSenderId:"411133047344",appId:"1:411133047344:web:07c250e162cde4d63cb3f5"};
const app=initializeApp(firebaseConfig),db=getFirestore(app);
document.getElementById("year").textContent=new Date().getFullYear();
const companyUrl="https://jmxdigitalcard.com/";
if(window.QRCode)new QRCode(document.getElementById("companyQr"),{text:companyUrl,width:160,height:160,colorDark:"#111111",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.H});
let platformSettings={};
try{const snap=await getDoc(doc(db,"platform","publicSettings"));platformSettings=snap.exists()?snap.data():{};const enabled=platformSettings.premiumEnabled===true;document.getElementById("premiumPlan").hidden=!enabled;document.getElementById("premiumSoon").hidden=enabled;const b=platformSettings.business||{};const businessReady=b.enabled===true&&b.policiesReady===true&&Boolean(b.privacyPolicy)&&Boolean(b.terms)&&Boolean(b.ctaUrl);const bp=document.getElementById("businessPlan");if(bp)bp.hidden=!businessReady;if(businessReady){document.getElementById("businessPlanNamePublic").textContent=b.planName||"JMX Business";document.getElementById("businessPlanTitlePublic").textContent=b.title||"Advanced networking for growing businesses";document.getElementById("businessPlanDescriptionPublic").textContent=b.description||"";document.getElementById("businessPlanPricePublic").textContent=b.price||"";document.getElementById("businessPlanFeaturesPublic").innerHTML=(b.features||[]).map(x=>`<li>${String(x).replace(/[&<>]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;"}[m]))}</li>`).join("");document.getElementById("businessCheckoutButton").textContent=b.ctaText||"Get JMX Business";}}catch(e){console.warn("Platform settings unavailable",e)}
const premiumBtn=document.getElementById("premiumCheckoutButton"),dialog=document.getElementById("premiumDialog"),agree=document.getElementById("privacyAgreement"),continueBtn=document.getElementById("continueToPayment"),policyLink=document.getElementById("privacyPolicyLink"),agreementCopy=document.getElementById("premiumAgreementCopy"),privacyRow=document.getElementById("privacyAgreementRow"),checkoutStatus=document.getElementById("checkoutStatus");
if(platformSettings.privacyAgreementText)agreementCopy.textContent=platformSettings.privacyAgreementText;if(platformSettings.privacyPolicyUrl)policyLink.href=platformSettings.privacyPolicyUrl;else policyLink.hidden=true;
function syncCheckout(){const required=platformSettings.privacyRequired!==false;privacyRow.hidden=!required;agree.required=required;continueBtn.disabled=required&&!agree.checked;}
agree?.addEventListener("change",syncCheckout);syncCheckout();
premiumBtn?.addEventListener("click",()=>{if(platformSettings.billingEnabled!==true){checkoutStatus.textContent="Premium checkout is not open yet.";}else checkoutStatus.textContent="";dialog?.showModal();});
continueBtn?.addEventListener("click",()=>{if(platformSettings.billingEnabled!==true){checkoutStatus.textContent="Premium checkout is not open yet.";return}if(platformSettings.privacyRequired!==false&&!agree.checked){checkoutStatus.textContent="Please accept the agreement to continue.";return}if(!platformSettings.premiumCheckoutUrl){checkoutStatus.textContent="Secure checkout has not been configured yet.";return}location.href=platformSettings.premiumCheckoutUrl;});

const businessBtn=document.getElementById("businessCheckoutButton"),businessDialog=document.getElementById("businessCheckoutDialog"),businessAgree=document.getElementById("businessAgreement"),continueBusiness=document.getElementById("continueBusiness"),businessStatus=document.getElementById("businessCheckoutStatus"),businessPolicyText=document.getElementById("businessPolicyPublicText");
businessAgree?.addEventListener("change",()=>{continueBusiness.disabled=!businessAgree.checked});
businessBtn?.addEventListener("click",()=>{businessStatus.textContent="";businessAgree.checked=false;continueBusiness.disabled=true;businessDialog?.showModal()});
document.getElementById("businessTermsButton")?.addEventListener("click",()=>{businessPolicyText.hidden=false;businessPolicyText.textContent=platformSettings.business?.terms||"Terms have not been published."});
document.getElementById("businessPrivacyButton")?.addEventListener("click",()=>{businessPolicyText.hidden=false;businessPolicyText.textContent=platformSettings.business?.privacyPolicy||"Privacy Policy has not been published."});
continueBusiness?.addEventListener("click",()=>{if(!businessAgree.checked){businessStatus.textContent="Please accept the Business Terms and Privacy Policy.";return}const url=platformSettings.business?.ctaUrl;if(!url){businessStatus.textContent="Business CTA is not configured.";return}location.href=url});
