"use strict";
const STORAGE_KEY="premiumDigitalCardProfile",THEME_KEY="digitalCardTheme";
const fallback={fullName:"John Smith",position:"Owner / Founder",company:"Premium Business LLC",city:"Chicago",state:"Illinois",description:"Professional services with quality, reliability and attention to detail.",phone:"(708) 555-1234",phoneRaw:"+17085551234",phone2:"",phone2Raw:"",whatsapp:"",whatsappRaw:"",email:"hello@example.com",website:"https://example.com",facebook:"",instagram:"",linkedin:"",twitter:"",tiktok:"",youtube:"",catalog:"",catalogFile:"",customBusinessLabel:"More Information",customBusinessSubtitle:"Open business link",customBusinessUrl:"",profileImage:"images/profile.jpg",coverImage:"images/cover.jpg",logoImage:"",galleryImages:[],videoUrl:"",service1Title:"Service One",service1Description:"Add a short description of your service here.",service1Icon:"fa-house",service2Title:"Service Two",service2Description:"Add another service description here.",service2Icon:"fa-screwdriver-wrench",service3Title:"Service Three",service3Description:"Customize this section for any type of business.",service3Icon:"fa-paint-roller",finalCtaTitle:"Let's Connect",finalCtaText:"Have a question or want to work together? Contact us today.",finalCtaLabel:"Contact Now",theme:"gold",visibility:{}};
function getProfile(){try{return {...fallback,...JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}"),visibility:{...(fallback.visibility||{}),...(JSON.parse(localStorage.getItem(STORAGE_KEY)||"{}").visibility||{})}}}catch(e){return {...fallback}}}
const p=getProfile();
function $id(id){return document.getElementById(id)} function text(id,v){const e=$id(id);if(e)e.textContent=v||""} function link(id,v){const e=$id(id);if(e)e.href=v||"#"} function visible(id,on){const e=$id(id);if(e)e.style.display=on?"":"none"} function has(v){return Boolean(v&&v!=="#")}
function cleanPhone(v){return (v||"").replace(/\D/g,"")} function displayWeb(v){return(v||"").replace(/^https?:\/\//i,"").replace(/\/$/,"")}
function pdfObjectURL(data){try{if(!data?.startsWith("data:application/pdf"))return data;const b=atob(data.split(",")[1]),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return URL.createObjectURL(new Blob([a],{type:"application/pdf"}))}catch(e){return""}}
function youtubeEmbed(url){if(!url)return"";try{const u=new URL(url);if(u.hostname.includes("youtu.be"))return"https://www.youtube.com/embed/"+u.pathname.slice(1);if(u.hostname.includes("youtube.com")){if(u.pathname.startsWith("/embed/"))return url;const v=u.searchParams.get("v");if(v)return"https://www.youtube.com/embed/"+v;const m=u.pathname.match(/\/shorts\/([^/?]+)/);if(m)return"https://www.youtube.com/embed/"+m[1]}return url}catch(e){return url}}
function applyData(){text("profileName",p.fullName);text("profilePosition",p.position);text("companyName",p.company);text("profileDescription",p.description);const loc=[p.city,p.state].filter(Boolean).join(", ");const pl=$id("profileLocation");if(pl){pl.innerHTML='<i class="fa-solid fa-location-dot"></i> '+loc}text("displayLocation",loc);text("displayPhone",p.phone);text("displayPhone2",p.phone2);text("displayWhatsApp",p.whatsapp||p.phone);text("displayEmail",p.email);text("displayWebsite",displayWeb(p.website));if($id("profilePhoto"))$id("profilePhoto").src=p.profileImage||"images/profile.jpg";if($id("coverImage"))$id("coverImage").src=p.coverImage||"images/cover.jpg";if(p.logoImage){$id("businessLogo").src=p.logoImage;$id("businessLogoWrapper").style.display="flex"}else visible("businessLogoWrapper",false);
link("phoneButton","tel:"+p.phoneRaw);link("textButton","sms:"+p.phoneRaw);link("emailButton","mailto:"+p.email);link("websiteButton",p.website);link("phone1Row","tel:"+p.phoneRaw);link("phone2Row","tel:"+p.phone2Raw);link("emailRow","mailto:"+p.email);link("websiteRow",p.website);const wa=p.whatsappRaw||p.phoneRaw;link("whatsappRow","https://wa.me/"+cleanPhone(wa));[["facebookLink",p.facebook],["instagramLink",p.instagram],["linkedinLink",p.linkedin],["twitterLink",p.twitter],["tiktokLink",p.tiktok],["youtubeLink",p.youtube]].forEach(([id,u])=>link(id,u));const cat=pdfObjectURL(p.catalogFile)||p.catalog;link("catalogLink",cat);text("customBusinessLabel",p.customBusinessLabel);text("customBusinessSubtitle",p.customBusinessSubtitle);link("customBusinessLink",p.customBusinessUrl);
for(let i=1;i<=3;i++){text(`service${i}Title`,p[`service${i}Title`]);text(`service${i}Description`,p[`service${i}Description`]);const ic=$id(`service${i}Icon`);if(ic)ic.className="fa-solid "+(p[`service${i}Icon`]||"fa-star")}
const vid=$id("featuredVideo");if(vid&&p.videoUrl)vid.src=youtubeEmbed(p.videoUrl);text("finalCtaTitle",p.finalCtaTitle);text("finalCtaText",p.finalCtaText);text("finalCtaLabel",p.finalCtaLabel);link("final-cta-button","tel:"+p.phoneRaw);loadGallery();applyVisibility(cat);applyTheme(p.theme||localStorage.getItem(THEME_KEY)||"gold")}
function loadGallery(){const imgs=Array.isArray(p.galleryImages)?p.galleryImages:[];document.querySelectorAll(".gallery-item").forEach((item,i)=>{const im=item.querySelector("img");if(imgs[i]){if(im)im.src=imgs[i];item.dataset.image=imgs[i];item.style.display=""}else if(imgs.length){item.style.display="none"}})}
function applyVisibility(cat){const v=p.visibility||{};visible("profileDescription",v.description!==false&&has(p.description));visible("businessLogoWrapper",v.logo!==false&&has(p.logoImage));visible("saveContactButton",v.saveContact!==false);visible("phoneButton",v.quickActions!==false&&v.phone!==false&&has(p.phoneRaw));visible("textButton",v.quickActions!==false&&v.phone!==false&&has(p.phoneRaw));visible("emailButton",v.quickActions!==false&&v.email!==false&&has(p.email));visible("websiteButton",v.quickActions!==false&&v.website!==false&&has(p.website));visible("quickActions",v.quickActions!==false&&["phoneButton","textButton","emailButton","websiteButton"].some(id=>$id(id)?.style.display!=="none"));visible("phone1Row",v.phone!==false&&has(p.phoneRaw));visible("phone2Row",v.phone2!==false&&has(p.phone2Raw));visible("whatsappRow",v.whatsapp!==false&&has(p.whatsappRaw||p.phoneRaw));visible("emailRow",v.email!==false&&has(p.email));visible("websiteRow",v.website!==false&&has(p.website));visible("locationRow",v.location!==false&&(has(p.city)||has(p.state)));visible("contactSection",["phone1Row","phone2Row","whatsappRow","emailRow","websiteRow","locationRow"].some(id=>$id(id)?.style.display!=="none"));const socials=[["facebookLink","facebook",p.facebook],["instagramLink","instagram",p.instagram],["linkedinLink","linkedin",p.linkedin],["twitterLink","twitter",p.twitter],["tiktokLink","tiktok",p.tiktok],["youtubeLink","youtube",p.youtube]];socials.forEach(([id,k,u])=>visible(id,v[k]!==false&&has(u)));visible("socialSection",socials.some(([id])=>$id(id)?.style.display!=="none"));visible("services",v.services!==false);visible("gallery",v.gallery!==false);visible("videoSection",v.video!==false&&has(p.videoUrl));visible("qrSection",v.qr!==false);visible("finalCtaSection",v.finalCTA!==false);visible("businessServicesLink",v.services!==false);visible("businessGalleryLink",v.gallery!==false);visible("catalogLink",v.catalog!==false&&has(cat));visible("customBusinessLink",v.customBusiness!==false&&has(p.customBusinessUrl));visible("businessLinksSection",v.businessLinks!==false&&["businessServicesLink","businessGalleryLink","catalogLink","customBusinessLink"].some(id=>$id(id)?.style.display!=="none"))}
const themes={gold:["#b88a2b","#e7cc84","#745317","184, 138, 43"],blue:["#2563eb","#93c5fd","#1e3a8a","37, 99, 235"],emerald:["#059669","#6ee7b7","#065f46","5, 150, 105"],purple:["#7c3aed","#c4b5fd","#4c1d95","124, 58, 237"],red:["#dc2626","#fca5a5","#7f1d1d","220, 38, 38"],black:["#171717","#a3a3a3","#050505","23, 23, 23"]};
function applyTheme(t){const a=themes[t]||themes.gold,r=document.documentElement;r.style.setProperty("--accent",a[0]);r.style.setProperty("--accent-light",a[1]);r.style.setProperty("--accent-dark",a[2]);r.style.setProperty("--accent-rgb",a[3]);localStorage.setItem(THEME_KEY,t);document.querySelectorAll(".theme-option").forEach(b=>b.classList.toggle("selected",b.dataset.theme===t))}
function initTheme(){const panel=$id("themePanel");$id("themeButton")?.addEventListener("click",()=>panel?.classList.add("active"));$id("closeThemePanel")?.addEventListener("click",()=>panel?.classList.remove("active"));document.querySelectorAll(".theme-option").forEach(b=>b.addEventListener("click",()=>{applyTheme(b.dataset.theme);panel?.classList.remove("active")}))}
function initGallery(){const lb=$id("lightbox"),li=$id("lightboxImage");document.querySelectorAll(".gallery-item").forEach(item=>item.addEventListener("click",()=>{if(!lb||!li)return;li.src=item.dataset.image||item.querySelector("img")?.src||"";lb.classList.add("active");lb.setAttribute("aria-hidden","false")}));$id("lightboxClose")?.addEventListener("click",()=>lb?.classList.remove("active"));lb?.addEventListener("click",e=>{if(e.target===lb)lb.classList.remove("active")})}
function cardURL(){return location.href.split("#")[0]}
async function shareCard(){const data={title:`${p.fullName} | ${p.company}`,text:"View my digital business card.",url:cardURL()};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast("Card link copied")}}catch(e){}}
function escapeVC(v){return String(v||"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function saveContact(){const lines=["BEGIN:VCARD","VERSION:3.0",`FN:${escapeVC(p.fullName)}`,`ORG:${escapeVC(p.company)}`,`TITLE:${escapeVC(p.position)}`,p.phoneRaw?`TEL;TYPE=CELL:${p.phoneRaw}`:"",p.phone2Raw?`TEL;TYPE=CELL:${p.phone2Raw}`:"",p.email?`EMAIL;TYPE=INTERNET:${p.email}`:"",p.website?`URL:${p.website}`:"",`ADR;TYPE=WORK:;;;${escapeVC(p.city)};${escapeVC(p.state)};;;`,`END:VCARD`].filter(Boolean).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines],{type:"text/vcard;charset=utf-8"}));a.download=(p.fullName||"contact").replace(/[^a-z0-9]+/gi,"-")+".vcf";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function initQR(){const q=$id("qrCode");if(!q||typeof QRCode==="undefined")return;q.innerHTML="";new QRCode(q,{text:cardURL(),width:160,height:160,colorDark:"#111111",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.H})}
function toast(m){let e=$id("toastMessage");if(!e){e=document.createElement("div");e.id="toastMessage";e.style.cssText="position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#111;color:#fff;padding:11px 16px;border-radius:12px;z-index:9999";document.body.appendChild(e)}e.textContent=m;e.style.display="block";clearTimeout(window._toast);window._toast=setTimeout(()=>e.style.display="none",2200)}
document.addEventListener("DOMContentLoaded",()=>{applyData();initTheme();initGallery();initQR();$id("shareButton")?.addEventListener("click",shareCard);$id("footerShareButton")?.addEventListener("click",shareCard);$id("saveContactButton")?.addEventListener("click",saveContact);text("currentYear",new Date().getFullYear())});
