import { initializeApp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-app.js";
import { getFirestore, doc, getDoc, getDocs, collection, setDoc, increment, serverTimestamp } from "https://www.gstatic.com/firebasejs/12.17.1/firebase-firestore.js";

const firebaseConfig={apiKey:"AIzaSyDf12K0m93K4cWSotDcSg2fIS-s3uaLW_Y",authDomain:"jmx-digital-card.firebaseapp.com",projectId:"jmx-digital-card",storageBucket:"jmx-digital-card.firebasestorage.app",messagingSenderId:"411133047344",appId:"1:411133047344:web:07c250e162cde4d63cb3f5"};
const app=initializeApp(firebaseConfig),db=getFirestore(app);
const LEGACY_STORAGE_KEY="premiumDigitalCardProfile",THEME_KEY="digitalCardTheme";
const params=new URLSearchParams(location.search);
const pathMatch=location.pathname.match(/^\/c\/([A-Za-z0-9_-]+)\/?$/);
const CARD_ID=sanitizeCardId(pathMatch?.[1]||params.get("card")||"main");
if(params.get("pretty")==="1"&&CARD_ID!=="main"&&!(["localhost","127.0.0.1"].includes(location.hostname)||location.hostname.endsWith("github.io"))) history.replaceState({},"",`/c/${CARD_ID}`);
const fallback={fullName:"",position:"",company:"",city:"",state:"",description:"",phone:"",phoneRaw:"",phone2:"",phone2Raw:"",whatsapp:"",whatsappRaw:"",email:"",website:"",facebook:"",instagram:"",linkedin:"",twitter:"",tiktok:"",youtube:"",catalog:"",catalogFile:"",customBusinessLabel:"",customBusinessSubtitle:"",customBusinessUrl:"",profileImage:"",coverImage:"",logoImage:"",galleryImages:[],videoUrl:"",service1Title:"",service1Description:"",service1Icon:"fa-house",service2Title:"",service2Description:"",service2Icon:"fa-screwdriver-wrench",service3Title:"",service3Description:"",service3Icon:"fa-paint-roller",finalCtaTitle:"Let's Connect",finalCtaText:"",finalCtaLabel:"Contact Now",theme:"gold",status:"active",visibility:{}}
let p={...fallback};
const FEATURE_KEYS=["description","saveContact","quickActions","phone","phone2","whatsapp","email","website","location","facebook","instagram","linkedin","twitter","tiktok","youtube","services","gallery","video","qr","finalCTA","businessLinks","catalog","customBusiness"];
const BASIC_FEATURE_DEFAULTS=new Set(["description","saveContact","quickActions","phone","whatsapp","email","location","facebook","qr"]);
function defaultFeatureControls(){const global={},Basic={},Premium={};FEATURE_KEYS.forEach(k=>{global[k]=true;Basic[k]=BASIC_FEATURE_DEFAULTS.has(k);Premium[k]=true});return{enabled:true,global,Basic,Premium}}
let platformFeatureControls=defaultFeatureControls();
function mergeFeatureControls(raw={}){const d=defaultFeatureControls();return{enabled:raw.enabled!==false,global:{...d.global,...(raw.global||{})},Basic:{...d.Basic,...(raw.Basic||{})},Premium:{...d.Premium,...(raw.Premium||{})}}}

function sanitizeCardId(v){const raw=String(v||"main").trim();if(raw.toLowerCase()==="main")return "main";return raw.toUpperCase().replace(/[^A-Z0-9_-]/g,"-").slice(0,64)||"main"}
function $id(id){return document.getElementById(id)} function text(id,v){const e=$id(id);if(e)e.textContent=v||""} function link(id,v){const e=$id(id);if(e)e.href=v||"#"} function visible(id,on){const e=$id(id);if(e)e.style.display=on?"":"none"} function has(v){return Boolean(v&&v!=="#")}
function cleanPhone(v){return(v||"").replace(/\D/g,"")} function displayWeb(v){return(v||"").replace(/^https?:\/\//i,"").replace(/\/$/,"")}
function getLegacy(){try{const x=JSON.parse(localStorage.getItem(LEGACY_STORAGE_KEY)||"{}");return {...fallback,...x,visibility:{...(fallback.visibility||{}),...(x.visibility||{})}}}catch{return {...fallback}}}
async function getOnlineProfile(){
  const [cardSnap,settingsSnap]=await Promise.all([getDoc(doc(db,"cards",CARD_ID)),getDoc(doc(db,"platform","publicSettings"))]);
  platformFeatureControls=mergeFeatureControls(settingsSnap.exists()?(settingsSnap.data().featureControls||{}):{});
  if(!cardSnap.exists())return null;
  const meta=cardSnap.data();
  if(["available","sold"].includes(meta.status))return {__activation:true,__meta:meta};
  if(["suspended","paused"].includes(meta.status))return {__suspended:true,__meta:meta};
  const profileSnap=await getDoc(doc(db,"profiles",CARD_ID));
  const data=profileSnap.exists()?profileSnap.data():meta;
  const out={...fallback,...data,status:meta.status||data.status||"activated",plan:meta.plan||"Premium",complimentaryPremium:meta.complimentaryPremium===true,subscription:meta.subscription||{},visibility:{...(fallback.visibility||{}),...(data.visibility||{})},galleryImages:[]};
  const ms=await getDocs(collection(db,"cards",CARD_ID,"media"));const gallery=[];
  ms.forEach(d=>{const m=d.data(),u=m.data||"";if(d.id==="logo")out.logoImage=u;else if(d.id==="profile")out.profileImage=u;else if(d.id==="cover")out.coverImage=u;else if(d.id==="catalog")out.catalogFile=u;else if(d.id.startsWith("gallery-")){const i=Number(d.id.split("-")[1]);if(Number.isInteger(i))gallery[i]=u}});
  out.galleryImages=gallery.filter(Boolean);return out
}

function monthKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function dayKey(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
async function trackMetric(action="view"){
  if(CARD_ID==="main") return;
  const base={cardId:CARD_ID,updatedAt:serverTimestamp()};
  const metric=action==="view"?{views:increment(1)}:{actions:{[action]:increment(1)}};
  const payload={...base,...metric};
  try{await Promise.all([
    setDoc(doc(db,"cardStats",CARD_ID),payload,{merge:true}),
    setDoc(doc(db,"monthlyStats",`${CARD_ID}_${monthKey()}`),payload,{merge:true}),
    setDoc(doc(db,"dailyStats",`${CARD_ID}_${dayKey()}`),payload,{merge:true})
  ])}catch(e){console.warn("Analytics skipped",e)}
}
function trackView(){return trackMetric("view")}
function initActionTracking(){
  const map={phoneButton:"phone",textButton:"text",emailButton:"email",websiteButton:"website",phone1Row:"phone",phone2Row:"phone",whatsappRow:"whatsapp",emailRow:"email",websiteRow:"website",facebookLink:"facebook",instagramLink:"instagram",linkedinLink:"linkedin",twitterLink:"twitter",tiktokLink:"tiktok",youtubeLink:"youtube",catalogLink:"catalog",customBusinessLink:"customLink",saveContactButton:"saveContact",shareButton:"share",footerShareButton:"share",finalCtaSection:"cta"};
  Object.entries(map).forEach(([id,name])=>$id(id)?.addEventListener("click",()=>trackMetric(name),{passive:true}));
}

function pdfObjectURL(data){try{if(!data?.startsWith("data:application/pdf"))return data;const b=atob(data.split(",")[1]),a=new Uint8Array(b.length);for(let i=0;i<b.length;i++)a[i]=b.charCodeAt(i);return URL.createObjectURL(new Blob([a],{type:"application/pdf"}))}catch{return""}}
function youtubeEmbed(url){if(!url)return"";try{const u=new URL(url);if(u.hostname.includes("youtu.be"))return"https://www.youtube.com/embed/"+u.pathname.slice(1);if(u.hostname.includes("youtube.com")){if(u.pathname.startsWith("/embed/"))return url;const v=u.searchParams.get("v");if(v)return"https://www.youtube.com/embed/"+v;const m=u.pathname.match(/\/shorts\/([^/?]+)/);if(m)return"https://www.youtube.com/embed/"+m[1]}return url}catch{return url}}
function setImage(id,src,fallbackText){const e=$id(id);if(!e)return;if(src){e.src=src;e.style.display=""}else{e.removeAttribute("src");e.style.display="none";if(fallbackText)e.alt=fallbackText}}
function applyData(){text("profileName",p.fullName);text("profilePosition",p.position);text("companyName",p.company);text("profileDescription",p.description);const loc=[p.city,p.state].filter(Boolean).join(", ");const pl=$id("profileLocation");if(pl)pl.innerHTML='<i class="fa-solid fa-location-dot"></i> '+loc;text("displayLocation",loc);text("displayPhone",p.phone);text("displayPhone2",p.phone2);text("displayWhatsApp",p.whatsapp||p.phone);text("displayEmail",p.email);text("displayWebsite",displayWeb(p.website));
setImage("profilePhoto",p.profileImage,p.fullName);setImage("coverImage",p.coverImage,"Cover image");
link("phoneButton","tel:"+p.phoneRaw);link("textButton","sms:"+p.phoneRaw);link("emailButton","mailto:"+p.email);link("websiteButton",p.website);link("phone1Row","tel:"+p.phoneRaw);link("phone2Row","tel:"+p.phone2Raw);link("emailRow","mailto:"+p.email);link("websiteRow",p.website);const wa=p.whatsappRaw||p.phoneRaw;link("whatsappRow","https://wa.me/"+cleanPhone(wa));[["facebookLink",p.facebook],["instagramLink",p.instagram],["linkedinLink",p.linkedin],["twitterLink",p.twitter],["tiktokLink",p.tiktok],["youtubeLink",p.youtube]].forEach(([id,u])=>link(id,u));const cat=pdfObjectURL(p.catalogFile)||p.catalog;link("catalogLink",cat);text("customBusinessLabel",p.customBusinessLabel);text("customBusinessSubtitle",p.customBusinessSubtitle);link("customBusinessLink",p.customBusinessUrl);
for(let i=1;i<=3;i++){text(`service${i}Title`,p[`service${i}Title`]);text(`service${i}Description`,p[`service${i}Description`]);const ic=$id(`service${i}Icon`);if(ic)ic.className="fa-solid "+(p[`service${i}Icon`]||"fa-star")}
const vid=$id("featuredVideo");if(vid){if(p.videoUrl){vid.src=youtubeEmbed(p.videoUrl);vid.style.display=""}else vid.removeAttribute("src")};text("finalCtaTitle",p.finalCtaTitle);text("finalCtaText",p.finalCtaText);text("finalCtaLabel",p.finalCtaLabel);link("final-cta-button","tel:"+p.phoneRaw);loadGallery();applyVisibility(cat);applyTheme(p.theme||"gold")}
function loadGallery(){const imgs=Array.isArray(p.galleryImages)?p.galleryImages:[];document.querySelectorAll(".gallery-item").forEach((item,i)=>{const im=item.querySelector("img");if(imgs[i]){if(im)im.src=imgs[i];item.dataset.image=imgs[i];item.style.display=""}else item.style.display="none"})}
function planAllows(feature){
  const planName=(p.complimentaryPremium===true?"Premium":(p.plan||"Premium"));
  if(platformFeatureControls.enabled===false){if(String(planName).toLowerCase()==="premium")return true;return BASIC_FEATURE_DEFAULTS.has(feature)}
  if(platformFeatureControls.global?.[feature]===false)return false;
  const bucket=String(planName).toLowerCase()==="basic"?platformFeatureControls.Basic:platformFeatureControls.Premium;
  return bucket?.[feature]!==false;
}
function applyVisibility(cat){const v=p.visibility||{};visible("profileDescription",planAllows("description")&&v.description!==false&&has(p.description));visible("saveContactButton",planAllows("saveContact")&&v.saveContact!==false);visible("phoneButton",planAllows("quickActions")&&planAllows("phone")&&v.quickActions!==false&&v.phone!==false&&has(p.phoneRaw));visible("textButton",planAllows("quickActions")&&planAllows("phone")&&v.quickActions!==false&&v.phone!==false&&has(p.phoneRaw));visible("emailButton",planAllows("quickActions")&&planAllows("email")&&v.quickActions!==false&&v.email!==false&&has(p.email));visible("websiteButton",planAllows("quickActions")&&planAllows("website")&&v.quickActions!==false&&v.website!==false&&has(p.website));visible("quickActions",v.quickActions!==false&&["phoneButton","textButton","emailButton","websiteButton"].some(id=>$id(id)?.style.display!=="none"));visible("phone1Row",planAllows("phone")&&v.phone!==false&&has(p.phoneRaw));visible("phone2Row",planAllows("phone2")&&v.phone2!==false&&has(p.phone2Raw));visible("whatsappRow",planAllows("whatsapp")&&v.whatsapp!==false&&has(p.whatsappRaw||p.phoneRaw));visible("emailRow",planAllows("email")&&v.email!==false&&has(p.email));visible("websiteRow",planAllows("website")&&v.website!==false&&has(p.website));visible("locationRow",planAllows("location")&&v.location!==false&&(has(p.city)||has(p.state)));visible("contactSection",["phone1Row","phone2Row","whatsappRow","emailRow","websiteRow","locationRow"].some(id=>$id(id)?.style.display!=="none"));const socials=[["facebookLink","facebook",p.facebook],["instagramLink","instagram",p.instagram],["linkedinLink","linkedin",p.linkedin],["twitterLink","twitter",p.twitter],["tiktokLink","tiktok",p.tiktok],["youtubeLink","youtube",p.youtube]];socials.forEach(([id,k,u])=>visible(id,planAllows(k)&&v[k]!==false&&has(u)));visible("socialSection",socials.some(([id])=>$id(id)?.style.display!=="none"));visible("services",planAllows("services")&&v.services!==false);visible("gallery",planAllows("gallery")&&v.gallery!==false&&Array.isArray(p.galleryImages)&&p.galleryImages.length>0);visible("videoSection",planAllows("video")&&v.video!==false&&has(p.videoUrl));visible("qrSection",planAllows("qr")&&v.qr!==false);visible("finalCtaSection",planAllows("finalCTA")&&v.finalCTA!==false);visible("businessServicesLink",planAllows("services")&&v.services!==false);visible("businessGalleryLink",planAllows("gallery")&&v.gallery!==false&&Array.isArray(p.galleryImages)&&p.galleryImages.length>0);visible("catalogLink",planAllows("catalog")&&v.catalog!==false&&has(cat));visible("customBusinessLink",planAllows("customBusiness")&&v.customBusiness!==false&&has(p.customBusinessUrl));visible("businessLinksSection",planAllows("businessLinks")&&v.businessLinks!==false&&["businessServicesLink","businessGalleryLink","catalogLink","customBusinessLink"].some(id=>$id(id)?.style.display!=="none"))}
const themes={gold:["#b88a2b","#e7cc84","#745317","184, 138, 43"],blue:["#2563eb","#93c5fd","#1e3a8a","37, 99, 235"],emerald:["#059669","#6ee7b7","#065f46","5, 150, 105"],purple:["#7c3aed","#c4b5fd","#4c1d95","124, 58, 237"],red:["#dc2626","#fca5a5","#7f1d1d","220, 38, 38"],black:["#171717","#a3a3a3","#050505","23, 23, 23"],cyan:["#06b6d4","#a5f3fc","#155e75","6, 182, 212"]};
function applyTheme(t){const a=themes[t]||themes.gold,r=document.documentElement;r.style.setProperty("--accent",a[0]);r.style.setProperty("--accent-light",a[1]);r.style.setProperty("--accent-dark",a[2]);r.style.setProperty("--accent-rgb",a[3]);document.querySelectorAll(".theme-option").forEach(b=>b.classList.toggle("selected",b.dataset.theme===t))}
function initTheme(){const panel=$id("themePanel");$id("themeButton")?.addEventListener("click",()=>panel?.classList.add("active"));$id("closeThemePanel")?.addEventListener("click",()=>panel?.classList.remove("active"));document.querySelectorAll(".theme-option").forEach(b=>b.addEventListener("click",()=>{applyTheme(b.dataset.theme);panel?.classList.remove("active")}))}
function initGallery(){const lb=$id("lightbox"),li=$id("lightboxImage");document.querySelectorAll(".gallery-item").forEach(item=>item.addEventListener("click",()=>{if(!lb||!li)return;li.src=item.dataset.image||item.querySelector("img")?.src||"";lb.classList.add("active");lb.setAttribute("aria-hidden","false")}));$id("lightboxClose")?.addEventListener("click",()=>lb?.classList.remove("active"));lb?.addEventListener("click",e=>{if(e.target===lb)lb.classList.remove("active")})}
function cardURL(){if(CARD_ID==="main")return location.origin+"/";if(["localhost","127.0.0.1"].includes(location.hostname)||location.hostname.endsWith("github.io"))return new URL(`card.html?card=${encodeURIComponent(CARD_ID)}`,location.href).href;return `${location.origin}/c/${CARD_ID}`}
async function shareCard(){const data={title:`${p.fullName} | ${p.company}`,text:"View my digital business card.",url:cardURL()};try{if(navigator.share)await navigator.share(data);else{await navigator.clipboard.writeText(data.url);toast("Card link copied")}}catch{}}
function escapeVC(v){return String(v||"").replace(/\\/g,"\\\\").replace(/\n/g,"\\n").replace(/,/g,"\\,").replace(/;/g,"\\;")}
function saveContact(){const lines=["BEGIN:VCARD","VERSION:3.0",`FN:${escapeVC(p.fullName)}`,`ORG:${escapeVC(p.company)}`,`TITLE:${escapeVC(p.position)}`,p.phoneRaw?`TEL;TYPE=CELL:${p.phoneRaw}`:"",p.phone2Raw?`TEL;TYPE=CELL:${p.phone2Raw}`:"",p.email?`EMAIL;TYPE=INTERNET:${p.email}`:"",p.website?`URL:${p.website}`:"",`ADR;TYPE=WORK:;;;${escapeVC(p.city)};${escapeVC(p.state)};;;`,"END:VCARD"].filter(Boolean).join("\r\n");const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([lines],{type:"text/vcard;charset=utf-8"}));a.download=(p.fullName||"contact").replace(/[^a-z0-9]+/gi,"-")+".vcf";a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)}
function initQR(){const q=$id("qrCode");if(!q||typeof QRCode==="undefined")return;q.innerHTML="";new QRCode(q,{text:cardURL(),width:160,height:160,colorDark:"#111111",colorLight:"#ffffff",correctLevel:QRCode.CorrectLevel.H})}
function toast(m){let e=$id("toastMessage");if(!e){e=document.createElement("div");e.id="toastMessage";e.style.cssText="position:fixed;left:50%;bottom:24px;transform:translateX(-50%);background:#111;color:#fff;padding:11px 16px;border-radius:12px;z-index:9999";document.body.appendChild(e)}e.textContent=m;e.style.display="block";clearTimeout(window._toast);window._toast=setTimeout(()=>e.style.display="none",2200)}
function showUnavailable(title,message){const app=document.querySelector(".digital-card-app");if(app)app.style.display="none";const box=document.createElement("main");box.className="public-status-screen";box.innerHTML=`<div class="public-status-card"><div class="public-status-icon"><i class="fa-regular fa-address-card"></i></div><h1>${title}</h1><p>${message}</p><a href="https://jmxdigitalcard.com">JMX Digital Card</a></div>`;document.body.appendChild(box);document.body.classList.remove("firebase-loading")}
async function boot(){
  document.body.classList.add("firebase-loading");let remote=null;
  try{remote=await getOnlineProfile()}catch(e){console.error("Firebase load failed",e)}
  if(!remote){const localHost=["localhost","127.0.0.1"].includes(location.hostname);if(localHost)remote=getLegacy();else return showUnavailable("Card not found","This JMX Digital Card code does not exist.")}
  if(remote.__activation){const app=document.querySelector(".digital-card-app");if(app)app.style.display="none";const box=document.createElement("main");box.className="public-status-screen";box.innerHTML=`<div class="public-status-card"><div class="public-status-icon"><i class="fa-solid fa-wifi"></i></div><h1>Activate your JMX Digital Card</h1><p>This NFC card is ready to be claimed by its owner.</p><a class="activation-link" href="/activate.html?card=${encodeURIComponent(CARD_ID)}">Activate Card</a><p style="margin-top:18px"><a href="/login.html">Owner Login</a></p></div>`;document.body.appendChild(box);document.body.classList.remove("firebase-loading");return}
  if(remote.__suspended)return showUnavailable("Card temporarily unavailable","This JMX Digital Card is currently suspended.");
  p=remote;applyData();initTheme();initGallery();initQR();trackView();initActionTracking();$id("shareButton")?.addEventListener("click",shareCard);$id("footerShareButton")?.addEventListener("click",shareCard);$id("saveContactButton")?.addEventListener("click",saveContact);text("currentYear",new Date().getFullYear());const owner=document.createElement("a");owner.href="/login.html";owner.textContent="Owner Login";owner.className="owner-login-link";document.body.appendChild(owner);document.body.classList.remove("firebase-loading")
}
document.addEventListener("DOMContentLoaded",boot);
